---
baseURL: "https://guidefari.com"
languageCode: en-us
title: Guide Fari
copyright: © Guide Fari
enableRobotsTXT: true
# code highlight
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pagination:
  pagerSize: 10
# Your Google analytics code.
googleAnalytics: "G-QNKPVT1XN3"
enableGitInfo: true
params:
  # mode can be auto or toggle
  mode: auto
  useCDN: true
  subtitle: "software engineering, music, & everything between"
  social:
    - name: GitHub
      icon: github
      url: "https://github.com/guidefari"
    - name: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/guide-fari-8b0063176/"
    - name: Twitter
      icon: twitter
      url: "https://twitter.com/guidefari"
    - name: Youtube
      icon: youtube
      url: "https://twitter.com/guidefari"
  favicon: "favicon.png"
Permalinks:
  post: "/:filename/"
  album: "/:filename/"
  artist: "/:filename/"
  resource: "/:filename/"
  til: "/:filename/"
  track: "/:filename/"
  book: "/:filename/"
  podcast: "/:filename/"
  playlist: "/:filename/"
  mix: "/:filename/"
  note: "/:filename/"
  bliki: "/:filename/"

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate

outputs:
  home:
    - html
    - rss
  section:
    - html
    - rss
  taxonomy:
    - html
    - rss
  term:
    - html
    - rss