// URL scheme for entries:
//
// Flattened sections (media, note, til, book, resource, ...)  →  /slug/
// Nested sections  (projects, docker-presentation, ...)       →  /section/slug/
// Root pages       (files at src/content/root.md)             →  /slug/
//
// Both URL shapes work for flattened sections:
//   /slug/           canonical (generated by [slug]/index.astro)
//   /section/slug/   alias (redirects via [...alias].astro)
//
// Additional aliases come from entry frontmatter `aliases` or the legacyAliases table below.

import { getCollection, getEntry } from "astro:content";
import { flattenedSections, sectionMeta, site } from "./site.mjs";

const collectionName = "entries";
const indexPages = new Map();

export function slugify(value) {
  return String(value ?? "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

export function tagSlugify(value) {
  return String(value ?? "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9_]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

function titleize(value) {
  return String(value ?? "")
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function trimSlashes(value) {
  return String(value ?? "").replace(/^\/+|\/+$/g, "");
}

function withTrailingSlash(value) {
  const path = `/${trimSlashes(value)}`;
  return path === "/" ? path : `${path}/`;
}

function readDate(value) {
  if (!value) return undefined;
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.valueOf()) ? undefined : date;
}

function sortByDateDesc(a, b) {
  return (b.date?.valueOf() ?? 0) - (a.date?.valueOf() ?? 0);
}

function normalizeTags(tags) {
  if (!tags) return [];
  if (Array.isArray(tags)) return tags.filter(Boolean).map(String);
  return [String(tags)];
}

function normalizeAliases(value) {
  if (!value) return [];
  const aliases = Array.isArray(value) ? value : [value];
  return aliases
    .filter(Boolean)
    .map((alias) => withTrailingSlash(alias))
    .filter((alias) => alias !== "//");
}

function buildEntry(astroEntry) {
  const id = astroEntry.id;
  const parts = id.split("/");
  const filename = parts.at(-1) ?? "";
  const basename = filename;
  const section = parts.length > 1 ? parts[0] : "";
  const isIndex = basename === "_index";
  const isRootPage = parts.length === 1;

  const slug = slugify(basename);
  let permalink;
  if (isRootPage) permalink = withTrailingSlash(slug);
  else if (flattenedSections.has(section)) permalink = withTrailingSlash(slug);
  else permalink = withTrailingSlash(`${section}/${slug}`);

  const data = astroEntry.data ?? {};
  const body = astroEntry.body ?? "";

  return {
    id,
    section,
    basename,
    slug,
    permalink,
    isIndex,
    isRootPage,
    title: data.title ?? titleize(basename),
    description: data.description ?? data.summary ?? "",
    date: readDate(data.date ?? data.publishDate ?? data.lastmod),
    draft: data.draft === true,
    tags: normalizeTags(data.tags),
    aliases: normalizeAliases(data.aliases),
    layout: data.layout ?? "",
    images: Array.isArray(data.images) ? data.images : [],
    hasMermaid: body.includes("```mermaid"),
    hasBody: body.trim().length > 0,
    data,
    body,
    _entry: astroEntry,
  };
}

let cachedEntries = null;
let cachedAll = null;
let cachedFlat = null;
let cachedSections = null;

async function loadAll() {
  if (cachedEntries) return cachedEntries;
  const raw = await getCollection(collectionName);
  const entries = raw.map(buildEntry);
  cachedEntries = entries;
  for (const entry of entries) {
    if (entry.isIndex && entry.section) indexPages.set(entry.section, entry);
  }
  return entries;
}

function allSorted() {
  if (!cachedAll) cachedAll = [...cachedEntries].sort(sortByDateDesc);
  return cachedAll;
}

function flatEntries() {
  if (!cachedFlat) {
    cachedFlat = cachedEntries.filter(
      (entry) => entry.isRootPage || flattenedSections.has(entry.section)
    );
  }
  return cachedFlat;
}

function sections() {
  if (!cachedSections) {
    cachedSections = [
      ...new Set(cachedEntries.map((entry) => entry.section).filter(Boolean)),
    ].sort();
  }
  return cachedSections;
}

export async function getAllEntries() {
  await loadAll();
  return allSorted();
}

export async function getEntryByPermalink(permalink) {
  await loadAll();
  const target = withTrailingSlash(permalink);
  return allSorted().find((entry) => entry.permalink === target);
}

export async function getFlatEntries() {
  await loadAll();
  return flatEntries();
}

export async function getNestedEntries(section) {
  await loadAll();
  return allSorted().filter(
    (entry) => entry.section === section && !flattenedSections.has(section)
  );
}

export async function getEntriesBySection(section) {
  await loadAll();
  return cachedEntries
    .filter((entry) => entry.section === section)
    .sort(sortByDateDesc);
}

export async function getSections() {
  await loadAll();
  return sections();
}

export async function getSectionInfo(section) {
  await loadAll();
  const index = indexPages.get(section);
  const meta = sectionMeta[section];
  return {
    title: index?.title ?? meta?.label ?? titleize(section),
    description: index?.description ?? meta?.description ?? "",
  };
}

export async function getAllTags() {
  await loadAll();
  const tags = new Map();
  for (const entry of cachedEntries) {
    for (const tag of entry.tags) {
      const slug = tagSlugify(tag);
      const current = tags.get(slug);
      if (current) {
        current.count += 1;
      } else {
        tags.set(slug, { slug, label: tag, count: 1 });
      }
    }
  }
  for (const tag of legacyTags) {
    if (!tags.has(tag)) tags.set(tag, { slug: tag, label: tag, count: 0 });
  }
  return [...tags.values()].sort(
    (a, b) => b.count - a.count || a.label.localeCompare(b.label)
  );
}

export async function getEntriesByTag(tagSlug) {
  await loadAll();
  return cachedEntries
    .filter((entry) => entry.tags.some((tag) => tagSlugify(tag) === tagSlug))
    .sort(sortByDateDesc);
}

export async function getAliasTargets() {
  await loadAll();
  const reserved = new Set(cachedEntries.map((entry) => entry.permalink));
  const aliases = new Map(legacyAliases);

  for (const entry of cachedEntries) {
    for (const alias of entry.aliases) {
      if (!reserved.has(alias)) aliases.set(alias, entry.permalink);
    }
    if (flattenedSections.has(entry.section) && entry.section) {
      const sectionAlias = withTrailingSlash(`${entry.section}/${entry.slug}`);
      if (!reserved.has(sectionAlias)) aliases.set(sectionAlias, entry.permalink);
    }
  }

  return [...aliases.entries()].map(([alias, target]) => ({ alias, target }));
}

export const legacySections = ["podcast", "tweet"];

const legacyTags = [
  "components",
  "correctness",
  "kiro",
  "michael-arnaldi",
  "open-source",
  "pattern-matching",
  "script",
  "series",
  "software-engineering",
  "tools",
  "tyepescript",
  "types",
  "youtube",
];

const legacyAliases = [
  ["/book-notes/", "/book/"],
  ["/10xts/", "/note/"],
  ["/ai-changes-the-balance-of-debt/", "/three-debts/"],
  ["/kiro-shell-startup/", "/bench-shell-startup/"],
  ["/otel-me-more/", "/pulse/"],
  ["/read/page/1/", "/read/"],
  ["/read/page/2/", "/read/"],
  ["/read/page/3/", "/read/"],
  ["/read/testing-react/", "/read/"],
  ["/tweet/opencode-references/", "/opencode-references/"],
  ["/docker-presentation/scripts/01-dockerception-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/02-linux-filesystem-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/03-container-chroot-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/04-container-namespaces-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/05-container-cgroups-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/06-dockerfile-basics-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/07-dockerfile-execution-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/08-multi-stage-small-containers-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/09-copy-gotchas-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/10-docker-compose-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/11-volumes-persistence-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/12-container-runtimes-script/", "/docker-presentation/"],
  ["/docker-presentation/scripts/13-complete-picture-script/", "/docker-presentation/"],
  ["/docker-presentation/series-guide/", "/docker-presentation/"],
];

export function getCanonicalUrl(pathname) {
  return new URL(pathname, site.url).toString();
}

export async function getEntryHtml(entry) {
  if (!entry?._entry) return entry?.description ?? "";
  const { render } = await import("astro:content");
  const { experimental_AstroContainer } = await import("astro/container");
  const { Content } = await render(entry._entry);
  const container = await experimental_AstroContainer.create();
  return await container.renderToString(Content);
}

export function getOgImage(entry) {
  if (entry?.images?.length) return entry.images[0];
  const title = entry?.title ?? site.title;
  return `https://images-here-hugo.vercel.app/api/og-image?title=${encodeURIComponent(title)}`;
}

export function formatDate(date, options = {}) {
  if (!date) return "";
  return new Intl.DateTimeFormat("en", options).format(date);
}
